"""创建tme_index表

Revision ID: 4b33da49dd85
Revises: 
Create Date: 2025-02-18 12:39:36.840521

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b33da49dd85'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tme_index',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('username', sa.String(length=32), nullable=False),
    sa.Column('type', sa.Enum('GROUP', 'CHANNEL', name='tmeindextype', length=32), nullable=False),
    sa.Column('nickname', sa.String(length=255), nullable=False),
    sa.Column('desc', sa.String(length=255), nullable=False),
    sa.Column('count_members', sa.Integer(), nullable=False),
    sa.Column('count_view', sa.Integer(), nullable=False),
    sa.Column('invalid_at', sa.DateTime(), nullable=True),
    sa.Column('last_gather_at', sa.DateTime(), nullable=True),
    sa.Column('create_at', sa.DateTime(), nullable=False),
    sa.Column('update_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tme_index_create_at'), 'tme_index', ['create_at'], unique=False)
    op.create_index(op.f('ix_tme_index_id'), 'tme_index', ['id'], unique=False)
    op.create_index(op.f('ix_tme_index_type'), 'tme_index', ['type'], unique=False)
    op.create_index(op.f('ix_tme_index_update_at'), 'tme_index', ['update_at'], unique=False)
    op.create_index(op.f('ix_tme_index_username'), 'tme_index', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tme_index_username'), table_name='tme_index')
    op.drop_index(op.f('ix_tme_index_update_at'), table_name='tme_index')
    op.drop_index(op.f('ix_tme_index_type'), table_name='tme_index')
    op.drop_index(op.f('ix_tme_index_id'), table_name='tme_index')
    op.drop_index(op.f('ix_tme_index_create_at'), table_name='tme_index')
    op.drop_table('tme_index')
    # ### end Alembic commands ###
