"""add_tme_index表新增gather_at字段

Revision ID: 525d50f554ce
Revises: d353c2eab4fb
Create Date: 2025-02-19 16:29:36.880924

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '525d50f554ce'
down_revision: Union[str, None] = 'd353c2eab4fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('add_tme_index', sa.Column('gather_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_add_tme_index_gather_at'), 'add_tme_index', ['gather_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_add_tme_index_gather_at'), table_name='add_tme_index')
    op.drop_column('add_tme_index', 'gather_at')
    # ### end Alembic commands ###
