"""tme_index表invalid_at、last_gather_at字段增加index索引

Revision ID: 77c0ee2ee6cc
Revises: 4b33da49dd85
Create Date: 2025-02-18 12:41:27.922699

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '77c0ee2ee6cc'
down_revision: Union[str, None] = '4b33da49dd85'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_tme_index_invalid_at'), 'tme_index', ['invalid_at'], unique=False)
    op.create_index(op.f('ix_tme_index_last_gather_at'), 'tme_index', ['last_gather_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tme_index_last_gather_at'), table_name='tme_index')
    op.drop_index(op.f('ix_tme_index_invalid_at'), table_name='tme_index')
    # ### end Alembic commands ###
