"""创建query_data表

Revision ID: 85116d4c89d7
Revises: 525d50f554ce
Create Date: 2025-02-21 09:36:47.787621

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '85116d4c89d7'
down_revision: Union[str, None] = '525d50f554ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('query_data',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('parameter', sa.JSON(), nullable=False),
    sa.Column('create_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_query_data_create_at'), 'query_data', ['create_at'], unique=False)
    op.create_index(op.f('ix_query_data_id'), 'query_data', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_query_data_id'), table_name='query_data')
    op.drop_index(op.f('ix_query_data_create_at'), table_name='query_data')
    op.drop_table('query_data')
    # ### end Alembic commands ###
