"""修改add_tme_index表名到user_add_index

Revision ID: b70021ca10b6
Revises: 6b088fcd5735
Create Date: 2025-02-27 16:46:04.795313

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'b70021ca10b6'
down_revision: Union[str, None] = '6b088fcd5735'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_add_index',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('username', sa.String(length=32), nullable=False),
    sa.Column('user_chat_id', sa.BigInteger(), nullable=True),
    sa.Column('gather_at', sa.DateTime(), nullable=True),
    sa.Column('create_at', sa.DateTime(), nullable=False),
    sa.Column('update_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_add_index_create_at'), 'user_add_index', ['create_at'], unique=False)
    op.create_index(op.f('ix_user_add_index_gather_at'), 'user_add_index', ['gather_at'], unique=False)
    op.create_index(op.f('ix_user_add_index_id'), 'user_add_index', ['id'], unique=False)
    op.create_index(op.f('ix_user_add_index_update_at'), 'user_add_index', ['update_at'], unique=False)
    op.create_index(op.f('ix_user_add_index_user_chat_id'), 'user_add_index', ['user_chat_id'], unique=False)
    op.create_index(op.f('ix_user_add_index_username'), 'user_add_index', ['username'], unique=False)
    op.drop_index('ix_add_tme_index_create_at', table_name='add_tme_index')
    op.drop_index('ix_add_tme_index_gather_at', table_name='add_tme_index')
    op.drop_index('ix_add_tme_index_id', table_name='add_tme_index')
    op.drop_index('ix_add_tme_index_update_at', table_name='add_tme_index')
    op.drop_index('ix_add_tme_index_user_chat_id', table_name='add_tme_index')
    op.drop_index('ix_add_tme_index_username', table_name='add_tme_index')
    op.drop_table('add_tme_index')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('add_tme_index',
    sa.Column('id', mysql.VARCHAR(collation='utf8mb4_bin', length=36), nullable=False),
    sa.Column('username', mysql.VARCHAR(collation='utf8mb4_bin', length=32), nullable=False),
    sa.Column('user_chat_id', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True),
    sa.Column('create_at', mysql.DATETIME(), nullable=False),
    sa.Column('update_at', mysql.DATETIME(), nullable=False),
    sa.Column('gather_at', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_bin',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_add_tme_index_username', 'add_tme_index', ['username'], unique=False)
    op.create_index('ix_add_tme_index_user_chat_id', 'add_tme_index', ['user_chat_id'], unique=False)
    op.create_index('ix_add_tme_index_update_at', 'add_tme_index', ['update_at'], unique=False)
    op.create_index('ix_add_tme_index_id', 'add_tme_index', ['id'], unique=False)
    op.create_index('ix_add_tme_index_gather_at', 'add_tme_index', ['gather_at'], unique=False)
    op.create_index('ix_add_tme_index_create_at', 'add_tme_index', ['create_at'], unique=False)
    op.drop_index(op.f('ix_user_add_index_username'), table_name='user_add_index')
    op.drop_index(op.f('ix_user_add_index_user_chat_id'), table_name='user_add_index')
    op.drop_index(op.f('ix_user_add_index_update_at'), table_name='user_add_index')
    op.drop_index(op.f('ix_user_add_index_id'), table_name='user_add_index')
    op.drop_index(op.f('ix_user_add_index_gather_at'), table_name='user_add_index')
    op.drop_index(op.f('ix_user_add_index_create_at'), table_name='user_add_index')
    op.drop_table('user_add_index')
    # ### end Alembic commands ###
