"""tme_index表去掉desc非空

Revision ID: cfb380a912f7
Revises: 77c0ee2ee6cc
Create Date: 2025-02-19 03:23:12.524995

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cfb380a912f7'
down_revision: Union[str, None] = '77c0ee2ee6cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
