"""创建add_tme_index表

Revision ID: d353c2eab4fb
Revises: cfb380a912f7
Create Date: 2025-02-19 16:25:40.451906

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd353c2eab4fb'
down_revision: Union[str, None] = 'cfb380a912f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('add_tme_index',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('username', sa.String(length=32), nullable=False),
    sa.Column('user_chat_id', sa.BigInteger(), nullable=True),
    sa.Column('create_at', sa.DateTime(), nullable=False),
    sa.Column('update_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_add_tme_index_create_at'), 'add_tme_index', ['create_at'], unique=False)
    op.create_index(op.f('ix_add_tme_index_id'), 'add_tme_index', ['id'], unique=False)
    op.create_index(op.f('ix_add_tme_index_update_at'), 'add_tme_index', ['update_at'], unique=False)
    op.create_index(op.f('ix_add_tme_index_user_chat_id'), 'add_tme_index', ['user_chat_id'], unique=False)
    op.create_index(op.f('ix_add_tme_index_username'), 'add_tme_index', ['username'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_add_tme_index_username'), table_name='add_tme_index')
    op.drop_index(op.f('ix_add_tme_index_user_chat_id'), table_name='add_tme_index')
    op.drop_index(op.f('ix_add_tme_index_update_at'), table_name='add_tme_index')
    op.drop_index(op.f('ix_add_tme_index_id'), table_name='add_tme_index')
    op.drop_index(op.f('ix_add_tme_index_create_at'), table_name='add_tme_index')
    op.drop_table('add_tme_index')
    # ### end Alembic commands ###
